name: to_do_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  google_fonts: ^5.1.0
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1
  flutter_localizations: # Add this line
    sdk: flutter
  uuid: ^4.2.1
  
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  multi_dropdown: ^2.1.3
  sqflite: ^2.3.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/fluent-mdl2_vacation.png
   - assets/images/Nothing to do.png
